[pytest]

addopts = -v

testpaths = tests

python_files = test_*.py

python_classes = Test*

python_functions = test_*

markers =
    
    tc_login_001: Verify User Login
    tc_login_002: Verify Login Page Displayed
    tc_login_003: Verify Email Field Visibility
    tc_login_004: Verify Password Field Visibility
    tc_login_005: Verify Login Button Visibility
    tc_login_006: Verify Forgot Password Link Visibility
    tc_login_007: Verify Register Link Visibility
    tc_login_008: Verify Required Field Validation
    tc_login_009: Verify Password Required Validation
    tc_login_010: Verify Password Policy Validation
    tc_login_011: Verify User Logout
    tc_dash_001:  Verify Dashboard Page Load
    tc_dash_002:  Verify Auto Refresh Checked By Default  
    tc_dash_003:  Verify Refresh Button Visibility
    tc_dash_004:  Verify Logout Button Visibility
    tc_dash_005:  Verify Dashboard Heading
    tc_dash_006:  Verify Total Employees Card  
    tc_dash_007:  Verify Active Employees Card
    tc_dash_008:  Verify Deliveries Today Card
    tc_dash_009:  Verify Failures Today Card
    tc_dash_010:  Verify Total Revenue Card
    tc_dash_011:  Verify MRR Card
    tc_dash_012:  Verify Active Subscriptions Card  
    tc_dash_013:  Verify On Trial Card
    tc_dash_014:  Verify Expiring Trials Card
    tc_dash_015:  Verify Plan Distribution Section
    tc_dash_016:  Verify Conversion Rate Section
    tc_dash_017:  Verify Updated Timestamp Display
    tc_companies_001: Verify user can navigate to Companies page
    tc_companies_002: Verify Companies page URL
    tc_companies_003: Verify Companies page heading
    tc_companies_004: Verify Total Companies card
    tc_companies_005: Verify Active card
    tc_companies_006: Verify On Trial card
    tc_companies_007: Verify Active Subscriptions card
    tc_companies_008: Verify Expired card

    